# Generated by Django 3.1.1 on 2020-09-21 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200919_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 14, 18, 57, 119945, tzinfo=utc)),
        ),
    ]
