# Generated by Django 3.1.1 on 2020-09-21 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200921_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 14, 19, 9, 574188, tzinfo=utc)),
        ),
    ]
